version: '3.8'

services:
  metadata-calculator:
    build: .
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "pnpm install && pnpm run dev --host 0.0.0.0"